### ISSUE TITLE
Check in

### ISSUE THREAD

**Issue by baverstrand** [Baverstrand/sofie-baverstrand-web-project#6]
Both input regarding Github setup and more general input would be helpful!

**Comment by gustavnyberg** [comment]
@Baverstrand 

My input is:

- Plus Menu = Nice to have and replaces Backlog for now, since this project will only have one iteration
- Bin = Won't do and replaces that for now
- Add swimlane Testing for now to clarify difference between Ready for Testing and Done, especially important if you have non tech and non developers using the board, since the doesn't seem to understand that an untested potentially finished feature is Done!

The log book looks to be very much in order! Yip for the future and for when like me using the working process and documentation in the the real world I recommend to create the date as the main headline and subheadlines for each time you make a new note during the day.  I myself always try to use at least morning, lunch break and end of workday (sometimes noting a nightly note when being on call and having to do an emergency departure for putting out some kind of fire)

The code looks well to. I would have asked for a bit more structure with folders and subfolders as well as a thought through structure about which files should go where. There are often to contradicting things to take into account. Sorting files in there actual logic function in the software or more conventional like splitting html, css, js and resources into different folders.. That is up to you.

I haven't read the code in detail and I won't. That will be a part of the video project pitch you are to send in together with the source code and I am looking forward to se your application in action as well as you walking me through your code.

Everything is aligned and in order to reach a VG, so it is all up to these last days, the tips you got and how you wrap it up and finally pitch it to me.

I know you've got it in you, so I really keep my fingers crossed for being able to give you that VG, if you come through and keep this solid performance up to and over the finish line tomorrow evening.

Good luck!
